# Generated by Django 4.1.1 on 2022-10-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_requesteduser_req_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteduser',
            name='req_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
