# Generated by Django 4.1.1 on 2022-10-21 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20221018_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension_end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 13, 17, 17, 505999)),
        ),
    ]
