# Generated by Django 4.1.1 on 2022-10-01 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_name', models.CharField(max_length=30)),
                ('account_desc', models.TextField(max_length=200)),
                ('account_category', models.CharField(max_length=15)),
                ('account_sub_category', models.CharField(max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=8, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dt_acct_creation', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
