# Generated by Django 4.1.1 on 2022-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_credit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_comment',
            field=models.TextField(default='Insert comment', max_length=200),
            preserve_default=False,
        ),
    ]
