# Generated by Django 4.1.1 on 2022-10-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_credit_or_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='statement_type',
            field=models.CharField(choices=[('IS', 'Income Statement'), ('BS', 'Balance Sheet'), ('RES', 'Retained Earnings Statement')], max_length=3),
        ),
    ]
