# Generated by Django 4.1.1 on 2022-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Marketable Securities', 'Market Securities'), ('Accounts Recievable', 'Accounts Recievable'), ('Inventory', 'Inventory'), ('Fixed Assets', 'Fixed Assets'), ('Goodwill', 'Goodwill')], default='Goodwill', max_length=21),
            preserve_default=False,
        ),
    ]
