# Generated by Django 4.1.1 on 2022-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_category',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Expenses', 'Expenses'), ('Equity', 'Equity'), ('Revenue', 'Revenue')], max_length=9),
        ),
    ]
