# Generated by Django 4.1.1 on 2022-10-07 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_alter_account_statement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Event_log',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('action_description', models.CharField(max_length=100)),
                ('account_source_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('user_source_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
