# Generated by Django 4.1.1 on 2022-10-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_event_log_account_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_event_log',
            name='account_source_id',
            field=models.IntegerField(),
        ),
    ]
