# Generated by Django 4.1.1 on 2022-10-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_alter_account_event_log_account_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('journal_entry_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('debit_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('credit_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('account_credit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_credit_id', to='accounts.account')),
                ('account_debit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_debit_id', to='accounts.account')),
            ],
        ),
    ]
