# Generated by Django 4.1.1 on 2022-10-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
