# Generated by Django 4.1.1 on 2022-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0002_journalentry_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('error_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('error_date_time', models.DateTimeField(auto_now_add=True)),
                ('error_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_comment',
            field=models.TextField(default='comment', max_length=200),
            preserve_default=False,
        ),
    ]
