# Generated by Django 4.1.1 on 2022-11-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0004_alter_transactionerror_error_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='initial_entry_subscription',
            field=models.CharField(default='initial comment placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
