# Generated by Django 4.1.1 on 2022-11-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0005_journalentry_initial_entry_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='initial_entry_subscription',
            new_name='initial_entry_description',
        ),
    ]
