# Generated by Django 4.1.1 on 2022-11-04 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals_and_ledgers', '0006_rename_initial_entry_subscription_journalentry_initial_entry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='approver_id',
            field=models.CharField(default='Unapproved', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user_submission_id',
            field=models.ForeignKey(default='787', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
