# Generated by Django 4.1.1 on 2022-11-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0011_journalentry_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reject_comment',
            field=models.TextField(default='This journal entry has not been rejected yet.', max_length=200),
        ),
    ]
