# Generated by Django 4.1.1 on 2022-11-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0012_journalentry_reject_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reject_comment',
            field=models.TextField(default='This journal entry has not been rejected yet or was approved.', max_length=200),
        ),
    ]
