# Generated by Django 4.1.1 on 2022-11-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals_and_ledgers', '0013_alter_journalentry_reject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='file',
            field=models.FileField(default='No File', upload_to=''),
            preserve_default=False,
        ),
    ]
